# Generated by Django 3.1.7 on 2021-03-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[(9, 'Юнусабадский район'), (8, 'Шайхантахурский район'), (4, 'Мирзо-Улугбекский район'), (10, 'Яккасарайский район'), (11, 'Яшнабадский район'), (2, 'Бектемирский район'), (6, 'Учтепинский район'), (5, 'Сергелийский район'), (7, 'Чиланзарский район'), (1, 'Алмазарский район'), (3, 'Мирабадский район')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'MALE')], max_length=10),
        ),
    ]
