# Generated by Django 3.1.7 on 2021-03-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210311_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[(1, 'Алмазарский район'), (9, 'Юнусабадский район'), (4, 'Мирзо-Улугбекский район'), (6, 'Учтепинский район'), (7, 'Чиланзарский район'), (3, 'Мирабадский район'), (11, 'Яшнабадский район'), (8, 'Шайхантахурский район'), (2, 'Бектемирский район'), (10, 'Яккасарайский район'), (5, 'Сергелийский район')], max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
