# Generated by Django 3.1.7 on 2021-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210312_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[(10, 'Яккасарайский район'), (8, 'Шайхантахурский район'), (5, 'Сергелийский район'), (1, 'Алмазарский район'), (6, 'Учтепинский район'), (7, 'Чиланзарский район'), (2, 'Бектемирский район'), (3, 'Мирабадский район'), (4, 'Мирзо-Улугбекский район'), (11, 'Яшнабадский район'), (9, 'Юнусабадский район')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'MALE')], max_length=10),
        ),
    ]
