# Generated by Django 3.1.7 on 2021-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210312_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[(7, 'Чиланзарский район'), (2, 'Бектемирский район'), (1, 'Алмазарский район'), (4, 'Мирзо-Улугбекский район'), (5, 'Сергелийский район'), (10, 'Яккасарайский район'), (11, 'Яшнабадский район'), (6, 'Учтепинский район'), (3, 'Мирабадский район'), (8, 'Шайхантахурский район'), (9, 'Юнусабадский район')], max_length=100),
        ),
    ]
