# Generated by Django 3.1.7 on 2021-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210312_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[(11, 'Яшнабадский район'), (4, 'Мирзо-Улугбекский район'), (3, 'Мирабадский район'), (6, 'Учтепинский район'), (1, 'Алмазарский район'), (7, 'Чиланзарский район'), (8, 'Шайхантахурский район'), (5, 'Сергелийский район'), (2, 'Бектемирский район'), (9, 'Юнусабадский район'), (10, 'Яккасарайский район')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('not_active', 'Not Active'), ('active', 'Active')], max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'MALE')], max_length=10),
        ),
    ]
