# Generated by Django 3.1.7 on 2021-03-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210312_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[(10, 'Яккасарайский район'), (11, 'Яшнабадский район'), (9, 'Юнусабадский район'), (1, 'Алмазарский район'), (2, 'Бектемирский район'), (4, 'Мирзо-Улугбекский район'), (7, 'Чиланзарский район'), (5, 'Сергелийский район'), (6, 'Учтепинский район'), (8, 'Шайхантахурский район'), (3, 'Мирабадский район')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active')], max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'MALE')], max_length=10),
        ),
    ]
