# Generated by Django 3.1.7 on 2021-03-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210312_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[(4, 'Мирзо-Улугбекский район'), (2, 'Бектемирский район'), (11, 'Яшнабадский район'), (10, 'Яккасарайский район'), (7, 'Чиланзарский район'), (5, 'Сергелийский район'), (9, 'Юнусабадский район'), (6, 'Учтепинский район'), (3, 'Мирабадский район'), (8, 'Шайхантахурский район'), (1, 'Алмазарский район')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('not_active', 'Not Active'), ('active', 'Active')], max_length=12),
        ),
    ]
