# Generated by Django 3.1.7 on 2021-03-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210312_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[(9, 'Юнусабадский район'), (4, 'Мирзо-Улугбекский район'), (7, 'Чиланзарский район'), (8, 'Шайхантахурский район'), (2, 'Бектемирский район'), (6, 'Учтепинский район'), (3, 'Мирабадский район'), (10, 'Яккасарайский район'), (5, 'Сергелийский район'), (1, 'Алмазарский район'), (11, 'Яшнабадский район')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'MALE')], max_length=10),
        ),
    ]
