# Generated by Django 3.1.7 on 2021-03-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210312_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[(1, 'Алмазарский район'), (10, 'Яккасарайский район'), (4, 'Мирзо-Улугбекский район'), (8, 'Шайхантахурский район'), (5, 'Сергелийский район'), (11, 'Яшнабадский район'), (3, 'Мирабадский район'), (6, 'Учтепинский район'), (2, 'Бектемирский район'), (9, 'Юнусабадский район'), (7, 'Чиланзарский район')], max_length=100),
        ),
    ]
